name: bi_dashboard
version: '1.0'
config-version: 2

profile: bi_dashboard

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
