version: 2

models:
  - name: order_summary_model
    description: "Aggregated order-level data with one row per order."
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: total_sales
        tests:
          - not_null
      - name: region
        tests:
          - accepted_values:
              values: ['East', 'West', 'Central', 'South']